#!/bin/sh

#
# No standard way to find boost, let's just try a bunch
# of options!
#
trial="/usr /usr/local /usr/local/opt /opt /opt/local /opt/homebrew /usr/local/homebrew"

if [ $# -ne 1 ]
then
	echo "Usage: $0 -i or $0 -l"
	exit 1
fi

case $1 in
-i) include=1;;
-l) include=0;;
*) echo "Usage: $0 -i or $0 -l"; exit 1;;
esac

for i in $trial
do
	if [ -d $i/include/boost ]
	then
		if [ $include -eq 1 ]
		then
			echo "-I${i}/include"
		else 
			echo "-L${i}/lib"
		fi
		exit 0
	fi
done

exit 1
